apiVersion: v1
kind: Service
metadata:
  name: dorms-service
  labels:
    app: dorms-service
spec:
  selector:
    app: dorms-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
