apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: booking-service:latest
          imagePullPolicy: Never
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: uniconnect.settings_booking
            - name: DATABASE_PATH
              value: /shared-data/db.sqlite3
            
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: media-storage
              mountPath: /app/media
            - name: shared-db
              mountPath: /shared-data
      volumes:
        - name: media-storage
          emptyDir: {}
        - name: shared-db
          persistentVolumeClaim:
            claimName: uniconnect-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
