apiVersion: apps/v1
kind: Deployment
metadata:
  name: dorm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dorm-service
  template:
    metadata:
      labels:
        app: dorm-service
    spec:
      containers:
        - name: dorm-service
          image: dorm-service:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: uniconnect.settings_dorm
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: media-storage
              mountPath: /app/media
      volumes:
        - name: media-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dorm-service
spec:
  selector:
    app: dorm-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
