apiVersion: apps/v1
kind: Deployment
metadata:
  name: dorm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dorm-service
  template:
    metadata:
      labels:
        app: dorm-service
    spec:
      containers:
        - name: dorm-service
          image: dorm-service:latest
          imagePullPolicy: Never
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: uniconnect.settings_dorm
            - name: DATABASE_PATH
              value: /shared-data/db.sqlite3
            - name: DJANGO_DEBUG              # ‚Üê ADD THESE 2 LINES
              value: "True"       
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: media-storage
              mountPath: /app/media
            - name: shared-db
              mountPath: /shared-data
      volumes:
        - name: media-storage
          emptyDir: {}
        - name: shared-db
          persistentVolumeClaim:
            claimName: uniconnect-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dorm-service
spec:
  selector:
    app: dorm-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP