apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: profile-service:latest
          imagePullPolicy: Never
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: uniconnect.settings_profile
            - name: DATABASE_PATH
              value: /shared-data/db.sqlite3
            
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: media-storage
              mountPath: /app/media
            - name: shared-db
              mountPath: /shared-data
      volumes:
        - name: media-storage
          emptyDir: {}
        - name: shared-db
          persistentVolumeClaim:
            claimName: uniconnect-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
