apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-service
  labels:
    app: profiles-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profiles-service
  template:
    metadata:
      labels:
        app: profiles-service
    spec:
      containers:
        - name: profiles
          image: profiles-service:latest
          imagePullPolicy: Never
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: services.profiles.settings
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
